services:
  agent:
    image: icr.io/instana/agent
    pid: "host"
    privileged: true
    volumes:
      - /var/run:/var/run
      - /run:/run
      - ./agent/configuration.yaml:/opt/instana/agent/etc/instana/configuration.yaml:ro
      # Include the File.cfg so spans are written to disk. We use them to verify which spans have been sent to the agent.
      - ./agent/com.instana.agent.main.sender.File.cfg:/opt/instana/agent/etc/instana/com.instana.agent.main.sender.File.cfg:ro
      # Mount the logs directly so we can directly access the span-*.log files to check the produced spans.
      - ./agent/logs:/opt/instana/agent/data/log
    networks:
      envoymesh:
        aliases:
          - instana-agent
    environment:
      - INSTANA_AGENT_ENDPOINT=${agent_endpoint:-ingress-red-saas.instana.io}
      - INSTANA_AGENT_ENDPOINT_PORT=${agent_endpoint_port:-443}
      - INSTANA_AGENT_KEY=${agent_key}
      - INSTANA_DOWNLOAD_KEY=${download_key}
      - INSTANA_AGENT_ZONE=${agent_zone:-php-otel-tracing-demo}
    healthcheck:
      test: ["CMD", "curl", "localhost:42699"]
      interval: 8s
      timeout: 10s
      retries: 5
    expose:
      - "42699"
      - "4317"
   
  db:
    image: mariadb:10.11.7
    command: '--default-authentication-plugin=mysql_native_password'
    network_mode: host
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress

  wordpress:
    build:
      context: .
      dockerfile: autoinstrumented-wordpress.dockerfile
    network_mode: host
    restart: always
    environment:
      - WORDPRESS_DB_HOST=127.0.0.1
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress

      # OTel auto instrumentation config
      # https://opentelemetry.io/docs/instrumentation/php/automatic/#installation
      - OTEL_PHP_AUTOLOAD_ENABLED=true
      - OTEL_SERVICE_NAME=php-wordpress-instana-otel-demo
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
      - INSTANA_PHP_SDK=enabled

volumes:
  db_data:
